export const itemInitialState = [
  {
    name: "Turtle",
    description: "A lovely turtle",
    collection: "Pins",
    dateCreated: new Date("2019-04-23").getTime(),
    dateModified: new Date("2019-04-23").getTime(),
    picture: "",
    city: "London",
    id: "_a5x31hxvnm8",
    image: "",
  },
  {
    name: "ZTurtle",
    description: "A lovely turtle",
    collection: "Pins",
    dateCreated: new Date("2018-02-21").getTime(),
    dateModified: new Date("2018-02-21").getTime(),
    picture: "",
    city: "London",
    id: "_y5d33hev3j6",
    image: "",
  },
  {
    name: "Hard Rock Amsterdam",
    description: "Guitar with stripes",
    collection: "Pins",
    dateCreated: new Date("2019-12-23").getTime(),
    dateModified: new Date("2019-12-23").getTime(),
    picture: "",
    city: "Amsterdam",
    id: "_mku890hj55s",
    image: "",
  },
  {
    name: "Hard Rock New York",
    description: "Blue Guitar",
    collection: "Pins",
    dateCreated: new Date("2013-01-28").getTime(),
    dateModified: new Date("2013-01-28").getTime(),
    picture: "",
    city: "New York",
    id: "_mkf892gj541",
    image: "",
  },
  {
    name: "A250e",
    description: "Hybrid Mercedes-Benz",
    collection: "Cars",
    dateCreated: new Date("2012-06-28").getTime(),
    dateModified: new Date("2012-06-28").getTime(),
    picture: "",
    city: "London",
    id: "_36v8a79vak8",
    image: "",
  },
];
